version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./ParceriaAnimal:/var/www/html
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=parceriaanimal

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parceriaanimal
    ports:
      - "3306:3306"
    volumes:
      - ./parceriaanimal.sql:/docker-entrypoint-initdb.d/init.sql
